In [4]:
# importing numpy library

import numpy as np

In [3]:
myList=[1,2,3,4,5]

arr=np.array(myList)

In [6]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4, 5])

In [11]:
arr.shape

(5,)

In [31]:
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[3,4,5,6,7]

arr=np.array([list1,list2,list3])


In [32]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [17]:
arr.shape

(3, 5)

In [18]:
#It just returns an array with the given shape 
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [24]:
#It doesnt change the array
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [18]:
## Accessing the array elements

arr=np.array([1,2,3,4,5,6,7,8,9])

In [29]:
arr[3]

4

In [34]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [40]:
arr[:,:]
print(arr[1:,3:])

[[5 6]
 [6 7]]


In [42]:
arr[:-1,:-1]

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [46]:
arr[1:,3:]

array([[5, 6],
       [6, 7]])

In [49]:
print(arr[1,1:4])
arr[1:,2:4]


[3 4 5]


array([[4, 5],
       [5, 6]])

In [54]:
arr=np.arange(0,10,step=2)

In [55]:
arr

array([0, 2, 4, 6, 8])

In [65]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [22]:
#copy function and broadcasting

print(arr)
arr[3:]=100
print(arr)

[  1   2   3 100 100 100 100 100 100]
[  1   2   3 100 100 100 100 100 100]


In [23]:
arr1=arr

In [24]:
arr[3:]=500
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [25]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [26]:
arr1=arr.copy()
print(arr)
arr[3:]=100
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[  1   2   3 500 500 500 500 500 500]


In [28]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [35]:
## some conditions very useful in Exploratory Data Analysis

val=2

print(arr<2)

print(arr[arr<10])

[ True False False False False False False False False]
[1 2 3]


In [42]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [44]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
## random distribution

np.random.rand(3,4)

array([[0.23270155, 0.98535478, 0.54224252, 0.23936437],
       [0.72891196, 0.69005585, 0.1092007 , 0.44955596],
       [0.81978255, 0.5227089 , 0.85929467, 0.72025065]])

In [188]:
arr_ex=np.random.randn(4,4)
np.random.randn()

0.32222669000207244

In [189]:
arr_ex

array([[-0.57710425, -0.76476217,  0.55199068,  0.16780648],
       [-0.86327933, -0.73917747,  0.2638139 , -0.85065475],
       [-0.76299631,  0.07548858, -1.49660602, -0.15199431],
       [-0.28137922, -0.24990288, -1.08260967,  0.97120657]])

In [8]:
# randint(low,high,size)

np.random.randint(0,100,8).reshape(4,2)

array([[ 4, 93],
       [ 6, 40],
       [60, 23],
       [58, 71]])

In [10]:
np.random.random_sample([1,5])

array([[0.74194557, 0.61799354, 0.48571067, 0.70198607, 0.07315731]])